# **NUMPY**

como su nombre indica, NumPy es un módulo de Python repleto de funciones útiles para trabajar con números. El "Num" en la primera parte del nombre NumPy significa números, y Py significa Python. Ahí lo tienes. Si tienes números y estás en Python, sabes qué necesitas importar. Correcto; necesitas importar NumPy, así de simple.


In [ ]:
pip install numpy

In [ ]:
import numpy as np

# La funcion arange()

Esta funcion produce una secuencia de numeros que van incrementando de manera constante. Ejemplos:

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(9, 201)

array([  9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,
        22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
        35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
        48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
        61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
        74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
        87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 18

# Funciones np.zeros() y np.ones()

crea un conjunto de elementos (ceros y unos) ordenados en filas y columnas, el cual recibe el nombre de **array** en ingles y se puede traducir  como **matriz** o **vector** al español.


In [ ]:
#Crearemos una matriz con 4 filas y 5 columnas llena de ceros.

np.zeros([4, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones([7,7]) #Crear un vector o matriz con 7 columnas y una unica fila.

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

En Numpy podemos hacer todo tipo de calculos matematicos y estadisticos para un conjunto de numeros, como calcular el promedio, la mediana, desviacion estandar, etc.

Las listas en Python son una de las estructuras de datos más versátiles y utilizadas. Son colecciones ordenadas, mutables y dinámicas que permiten almacenar elementos de diferentes tipos, por ejemplo numeros para realizar operaciones.


In [ ]:
listanumeros = [2,5,7,11,13,17,23,31,37,41,43,47]

np.mean(listanumeros)

np.float64(23.083333333333332)

In [ ]:
listanumeros = [2,5,7,11,13,17,23,31,37,41,43,47]
numeros = np.array(listanumeros)
numeros.mean()

np.float64(23.083333333333332)

In [ ]:
type(numeros)

numpy.ndarray

#Ejercicio

Dadas las calificaciones de 10 estudiantes, utilice NumPy para calcular el
promedio de sus calificaciones.

In [ ]:
estudiantes = ["Perla", "Juan", 'Cristian', 'Omar', 'Maria', 'Marisol', 'Pedro',
               'Ana', 'Sergio', 'Mariana']

matematicas = [8, 5, 6, 7, 6, 10, 7, 7, 6, 7]
quimica = [9, 8, 5, 5, 6, 5, 9, 7, 8, 8]
historia = [6, 9, 5, 9, 10, 10, 10, 10, 9, 7]

In [ ]:
len(estudiantes)

10

In [ ]:
promedios = np.zeros(10)
print(promedios)

for i in range(len(estudiantes)):
  promedios[i] = np.round(np.mean([matematicas[i], quimica[i], historia[i]]), 2)



print(promedios)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[7.67 7.33 5.33 7.   7.33 8.33 8.67 8.   7.67 7.33]


In [ ]:
for i in range(len(estudiantes)):
  print(f'El promedio de {estudiantes[i]} es : {promedios[i]}')

El promedio de Perla es : 7.67
El promedio de Juan es : 7.33
El promedio de Cristian es : 5.33
El promedio de Omar es : 7.0
El promedio de Maria es : 7.33
El promedio de Marisol es : 8.33
El promedio de Pedro es : 8.67
El promedio de Ana es : 8.0
El promedio de Sergio es : 7.67
El promedio de Mariana es : 7.33


# La funcion np.linspace()

Devuelve numeros espaciados uniformemente en un intervalo especificado. Esta funcion acepta tres entradas, las dos primeras especifican el intervalo y la tercera es el numero de elementos que tendra la salida. Ejemplo:

In [ ]:
np.linspace(0,1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [ ]:
np.linspace(10, 1000, 100)

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,
        100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,  180.,
        190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,  270.,
        280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,  360.,
        370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,  450.,
        460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,  540.,
        550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,  630.,
        640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,  720.,
        730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,  810.,
        820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,  900.,
        910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,  990.,
       1000.])

Esta funcion es muy util para situaciones en las que se necesita probar diferentes valores para encontrar el que mejor se adapte a las necesidades. Ejemplo:


Queremos encontrar los valores que satisfacen la siguiente ec.

$x^2 -5x + 6 = 0$

In [ ]:
posibles = np.linspace(-1000, 1000, 2001) #Probeamos todos los valores enteros entre el -mil y el mil

for posible in posibles:
  if(posible**2 - 5*posible + 6  == 0):
    print(f'Una posible respuesta es: {posible}')

Una posible respuesta es: 2.0
Una posible respuesta es: 3.0
